DROP TABLE IF EXISTS PIZZA_SALES;
CREATE TABLE IF NOT EXISTS PIZZA_SALES
( pizza_id INTEGER PRIMARY KEY,
  order_id INTEGER,
  pizza_name_id TEXT,
  quantity INTEGER,
  order_date DATE,
  order_time TIME,
  unit_price NUMERIC(10,2),
  total_price NUMERIC(10,2),
  pizza_size VARCHAR(10),
  pizza_category VARCHAR(50),
  pizza_ingredients TEXT,
  pizza_name TEXT
);
SELECT * FROM PIZZA_SALES;

--File Import--
--DIRECTLY

-- KPI's

-- 1.TOTAL REVENUE
SELECT SUM(total_price) AS TOTAL_REVENUE
FROM PIZZA_SALES;

-- 2.TOTAL ORDERS
SELECT COUNT(DISTINCT order_id) as TOTAL_ORDERS
FROM PIZZA_SALES;

-- 3.AVERAGE ORDER VALUE
SELECT CAST(
CAST(SUM(total_price) AS DECIMAL(10,2)) / 
CAST(COUNT(DISTINCT order_id) AS DECIMAL(10,2))
AS DECIMAL(10,2)) AS AVG_ORDER_VALUE
FROM PIZZA_SALES;

--4.TOTAL PIZZA SOLD
SELECT SUM(quantity) as TOTAL_PIZZA_SOLD
FROM PIZZA_SALES;

--5 AVERAGE PIZZA PER ORDER
SELECT SUM(quantity) / COUNT(DISTINCT ORDER_ID) AS AVG_PIZZA_PER_ORDER
FROM PIZZA_SALES;

--ANALYSIS

--1. MONTHLY TREND FOR TOTAL_REVENUE
SELECT TO_CHAR(order_date,'MONTH') AS MONTH, SUM(total_price) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY TO_CHAR(order_date,'MONTH'), EXTRACT(MONTH FROM order_date)
ORDER BY EXTRACT(MONTH FROM order_date);

--2. DAILY TREND FOR TOTAL ORDERS
SELECT TO_CHAR(order_date,'DAY') AS DAY, COUNT(DISTINCT order_id) as TOTAL_ORDER
FROM PIZZA_SALES
GROUP BY TO_CHAR(order_date,'DAY');

---3. PERCENTAGE OF SALES BY PIZZA CATEGORY
SELECT pizza_category, SUM(total_price) as TOTAL_REVENUE,
CAST(SUM(total_price)*100/
(SELECT SUM(total_price) FROM PIZZA_SALES) AS DECIMAL(10,2)) AS PERCENTAGE
FROM PIZZA_SALES
GROUP BY pizza_category;

--4. PERCENTAGE OF SALES BY PIZZA SIZE
SELECT pizza_size, SUM(total_price) as TOTAL_REVENUE,
CAST(SUM(total_price)*100/
(SELECT SUM(total_price) FROM PIZZA_SALES) AS DECIMAL(10,2)) AS PERCENTAGE
FROM PIZZA_SALES
GROUP BY pizza_size;

--5. TOTAL PIZZA SOLD BY PIZZA CATEGORY AND SIZE
SELECT pizza_category, SUM(quantity) as TOTAL_PIZZA_SALE
FROM PIZZA_SALES
GROUP BY pizza_category; 

SELECT pizza_size, SUM(quantity) as TOTAL_PIZZA_SALE
FROM PIZZA_SALES
GROUP BY pizza_size;

--6. REVENUE BY PIZZA NAME
SELECT pizza_name, SUM(total_price) as TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY pizza_name
ORDER BY TOTAL_REVENUE DESC;

--TOP AND BOTTOM ANALYSIS

--1. TOP 3 PIZZAS BY REVENUE
SELECT pizza_name, SUM(total_price) as TOP_REVENUE
FROM PIZZA_SALES
GROUP BY pizza_name
ORDER BY TOP_REVENUE DESC
LIMIT 1;

--2.BOTTOM 3 PIZZAS BY REVENUE
SELECT pizza_name, SUM(total_price) as TOP_REVENUE
FROM PIZZA_SALES
GROUP BY pizza_name
ORDER BY TOP_REVENUE
LIMIT 3;

--3. TOP 3 PIZZAS BY ORDERS
SELECT pizza_name, COUNT(DISTINCT ORDER_ID) as TOP_ORDERS
FROM PIZZA_SALES
GROUP BY pizza_name
ORDER BY TOP_ORDERS DESC
LIMIT 3; 

--4. BOTTOM 3 PIZZAS BY ORDERS
SELECT pizza_name, COUNT(DISTINCT ORDER_ID) as WORST_ORDERS
FROM PIZZA_SALES
GROUP BY pizza_name
ORDER BY WORST_ORDERS 
LIMIT 3; 

--5. TOP 3 PIZZAS BY QUANTITY SOLD
SELECT pizza_name, SUM(quantity) as TOP_PIZZA_QUANTITY
FROM PIZZA_SALES
GROUP BY pizza_name
ORDER BY TOP_PIZZA_QUANTITY DESC
LIMIT 3;

--6. BOTTOM 3 PIZZAS BY QUANTITY SOLD
SELECT pizza_name, SUM(quantity) as TOP_PIZZA_QUANTITY
FROM PIZZA_SALES
GROUP BY pizza_name
ORDER BY TOP_PIZZA_QUANTITY
LIMIT 3;


